D-Bus testing: need common '/' object for ConnMan and Bluez
Adding the always-on '/' object for ConnMan broke Bluez testing,
because adding a second '/' object for the Bluez calls fails with:
  KeyError: "Can't register the object-path handler for '/': there is already a handler"

This makes sense, because at the D-Bus message might be sent directly,
without including the well-known bus name, and thus finding the right
right object cannot be done by bus name.

Solved by registering a unified ConnMan/Bluez root object which provides
both interfaces.