WebDAV: ignore Radicale PROPFIND + allprops problem
The debug request failed with Radicale (details below). Now the result
of executing the request is ignored instead of failing the entire
operation.

PROPFIND /public_user/calendar/ HTTP/1.1

[<?xml version="1.0" encoding="utf-8"?>
<propfind xmlns="DAV:"><allprop/></propfind>
]

HTTP/1.0 500 Internal Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 183, in __call__
    status, headers, answer = function(environ, items, content, None)
  File "/usr/lib/python2.7/dist-packages/radicale/__init__.py", line 365, in propfind
    environ["PATH_INFO"], content, calendars, user)
  File "/usr/lib/python2.7/dist-packages/radicale/xmlutils.py", line 184, in propfind
    props = [prop.tag for prop in prop_element]
TypeError: 'NoneType' object is not iterable