autotools: add DBUS_LIBS to syncevo_dbus_server_LDADD
syncevo-dbus-server seems to be missing link info for dbus, without
this patch I get:
  /usr/bin/ld: syncevo_dbus_server-syncevo-dbus-server.o:
  undefined reference to symbol 'dbus_connection_ref'