configure: detect incorrect use of --with-synthesis-src
--with-synthesis-src requires a parameter. Without it, "yes"
was used as value, leading to a pretty obscure error message
about "no configure script in yes".

That error message should mention --with-synthesis-src. It now
says:
  error: --with-synthesis-src=/tmp: no Synthesis configure script found in that directory